### ISSUE TITLE
"Server didn't respond to modded handshake."

### ISSUE THREAD

**Issue by GABETROLL** [NuclearPowered/Reactor.Impostor#1]
I got this error for the first time today. I tried making a new test mod, and even the template creates this issue.

**Comment by js6pak** [comment]
Are you sure this is Reactor.Impostor issue? Are you sure you are connecting to the custom Impostor server that you made and installed Reactor.Impostor as a plugin to it? Are you sure that you are not connecting to the official servers?

**Comment by jellytoaster** [comment]
how about boot.handshake

**Comment by js6pak** [comment]
I'll just assume that you are the guy from discord and resolved your issue without reporting it back here, join the [discord](https://reactor.gg/discord) if you have problems still.
